# Generated by Django 5.0.6 on 2024-05-28 01:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateField(default=datetime.date(2024, 5, 27))),
                ('contacto', models.CharField(max_length=15)),
                ('contacto_de_emergencia', models.CharField(max_length=15)),
                ('imagen_de_perfil', models.ImageField(height_field=300, upload_to='./images', width_field=300)),
                ('ultimo_pago', models.DateField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='genero', to='api.genero')),
                ('estado_membresia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estado_membresia', to='api.miembroestado')),
                ('tipo_membresia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipo_membresia', to='api.miembrotipo')),
            ],
        ),
    ]
