# Generated by Django 5.0.6 on 2024-05-28 04:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('fecha_de_registro', models.DateField(default=datetime.date(2024, 5, 27))),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date(2024, 5, 27))),
                ('semanas', models.IntegerField(default=6)),
            ],
        ),
        migrations.RenameField(
            model_name='miembro',
            old_name='lastName',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='miembro',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_membresia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_membresia', to='api.miembroestado'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genero', to='api.genero'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='tipo_membresia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_membresia', to='api.miembrotipo'),
        ),
        migrations.AddIndex(
            model_name='miembro',
            index=models.Index(fields=['apellidos', 'nombre'], name='api_miembro_apellid_c101d4_idx'),
        ),
        migrations.AddIndex(
            model_name='miembro',
            index=models.Index(fields=['nombre'], name='nombre_idx'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='instructor', to='api.instructor'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembro', to='api.miembro'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='objetivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivo', to='api.objetivo'),
        ),
    ]
