# Generated by Django 5.0.6 on 2024-05-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_miembro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='images/', width_field=300),
        ),
    ]
