# Generated by Django 5.0.6 on 2024-05-28 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_miembro_imagen_de_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='contacto',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='contacto_de_emergencia',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genero', to='api.genero'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='ultimo_pago',
            field=models.DateField(null=True),
        ),
    ]
