# Generated by Django 5.0.6 on 2024-05-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_miembro_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='contacto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='contacto_de_emergencia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='ultimo_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
