# Generated by Django 5.0.6 on 2024-05-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_miembro_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
