# Generated by Django 5.0.6 on 2024-05-28 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_miembro_imagen_de_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicion',
            name='pantorrilla_derecha',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='pantorrilla_izquierda',
            field=models.FloatField(null=True),
        ),
    ]
