# Generated by Django 5.0.6 on 2024-05-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_instructor_usuario_medicion_pantorrilla_derecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='espalda',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rutina',
            unique_together={('fecha', 'miembro', 'instructor')},
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(fields=['fecha', 'miembro'], name='api_rutina_fecha_762887_idx'),
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(fields=['miembro'], name='api_rutina_miembro_ca926f_idx'),
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(fields=['fecha'], name='api_rutina_fecha_f6f198_idx'),
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(fields=['instructor'], name='api_rutina_instruc_24d3b5_idx'),
        ),
    ]
