# Generated by Django 5.0.6 on 2024-06-01 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_medicion_espalda_alter_rutina_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='miembro',
            index=models.Index(fields=['estado_membresia'], name='api_miembro_estado__c4cfad_idx'),
        ),
    ]
