# Generated by Django 5.0.6 on 2024-06-01 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_miembro_api_miembro_estado__c4cfad_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='estado_membresia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='estado_membresia', to='api.miembroestado'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='genero', to='api.genero'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='tipo_membresia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='tipo_membresia', to='api.miembrotipo'),
        ),
    ]
