# Generated by Django 5.0.6 on 2024-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_miembro_estado_membresia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
