# Generated by Django 5.0.6 on 2024-06-02 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_miembro_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='medicion',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.unidaddemedida'),
        ),
    ]
