# Generated by Django 5.0.6 on 2024-06-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_unidaddemedida_medicion_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidaddemedida',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unidaddemedida',
            name='simbolo',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
