# Generated by Django 5.0.6 on 2024-06-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_unidaddemedida_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='rutina',
        ),
    ]
