# Generated by Django 5.0.6 on 2024-06-08 21:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_medicion_brazo_derecho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('finalidad', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repeticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rutina',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='duracion',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.CreateModel(
            name='DiaDeRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutina', to='api.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentosDeEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio_instrumentos_de_ejercicio', to='api.ejercicio')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumento_instrumentos_de_ejercicio', to='api.instrumento')),
            ],
        ),
        migrations.CreateModel(
            name='MusculosDeEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio_musculos_de_ejercicio', to='api.ejercicio')),
                ('grupo_muscular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_muscular_musculos_de_ejercicio', to='api.grupomuscular')),
            ],
        ),
        migrations.CreateModel(
            name='MusculosPorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_de_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_de_rutina_musculos_por_dia', to='api.diaderutina')),
                ('grupo_muscular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_muscular_musculos_por_dia', to='api.grupomuscular')),
            ],
        ),
        migrations.CreateModel(
            name='RecursosDeEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio_recursos_de_ejercicio', to='api.ejercicio')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_recurso_recursos_de_ejercicio', to='api.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='EjerciciosPorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_de_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_de_rutina_ejercicios_por_dia', to='api.diaderutina')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio_ejercicios_por_dia', to='api.ejercicio')),
                ('repeticion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.repeticion')),
            ],
        ),
    ]
