# Generated by Django 5.0.6 on 2024-06-09 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_ejercicio_grupomuscular_instrumento_recurso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='url',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='diaderutina',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_de_rutina', to='api.rutina'),
        ),
        migrations.AlterField(
            model_name='grupomuscular',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
