# Generated by Django 5.0.6 on 2024-06-09 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_instrumento_url_instrumento_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='instrumentos/'),
        ),
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='musculos/')),
                ('grupo_muscular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupomuscular')),
            ],
        ),
    ]
