# Generated by Django 5.0.6 on 2024-06-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_musculo_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musculo',
            new_name='Musculos',
        ),
    ]
