# Generated by Django 5.0.6 on 2024-06-09 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_musculo_musculos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='musculos/')),
                ('grupo_muscular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupomuscular')),
            ],
        ),
        migrations.DeleteModel(
            name='Musculos',
        ),
    ]
