# Generated by Django 5.0.6 on 2024-06-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_musculo_funciones_principales_musculo_insercion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupomuscular',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='grupomuscular',
            name='comentario',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
