# Generated by Django 5.0.6 on 2024-06-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_grupomuscular_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='finalidad',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='comentarios',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='ejecucion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='errores_frequentes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
