# Generated by Django 5.0.6 on 2024-06-09 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_ejercicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='comentarios',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='ejecucion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='errores_frequentes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='musculosdeejercicio',
            name='grupo_muscular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_muscular_musculos_de_ejercicio', to='api.musculo'),
        ),
    ]
