# Generated by Django 5.0.6 on 2024-06-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_ejercicio_comentarios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musculosdeejercicio',
            old_name='grupo_muscular',
            new_name='musculo',
        ),
    ]
