# Generated by Django 5.0.6 on 2024-06-09 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_grupo_muscular_musculosdeejercicio_musculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musculosdeejercicio',
            name='musculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musculo', to='api.musculo'),
        ),
    ]
