# Generated by Django 5.0.6 on 2024-06-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_musculosdeejercicio_musculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejercicio',
            old_name='errores_frequentes',
            new_name='errores_frecuentes',
        ),
        migrations.AlterField(
            model_name='ejerciciospordia',
            name='dia_de_rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='api.diaderutina'),
        ),
        migrations.AlterField(
            model_name='ejerciciospordia',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ejercicio'),
        ),
        migrations.AlterField(
            model_name='instrumentosdeejercicio',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='api.instrumento'),
        ),
        migrations.AlterUniqueTogether(
            name='ejerciciospordia',
            unique_together={('dia_de_rutina', 'ejercicio')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumentosdeejercicio',
            unique_together={('ejercicio', 'instrumento')},
        ),
        migrations.AlterUniqueTogether(
            name='musculosdeejercicio',
            unique_together={('ejercicio', 'musculo')},
        ),
    ]
