# Generated by Django 5.0.6 on 2024-06-16 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_errores_frequentes_ejercicio_errores_frecuentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentosdeejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='api.ejercicio'),
        ),
        migrations.AlterField(
            model_name='instrumentosdeejercicio',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio', to='api.instrumento'),
        ),
        migrations.AlterField(
            model_name='musculosdeejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musculos', to='api.ejercicio'),
        ),
        migrations.AlterField(
            model_name='musculosdeejercicio',
            name='musculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio', to='api.musculo'),
        ),
        migrations.AlterField(
            model_name='musculospordia',
            name='dia_de_rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_musculares', to='api.diaderutina'),
        ),
        migrations.AlterField(
            model_name='musculospordia',
            name='grupo_muscular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia', to='api.grupomuscular'),
        ),
        migrations.AlterField(
            model_name='recursosdeejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='api.ejercicio'),
        ),
        migrations.AlterField(
            model_name='recursosdeejercicio',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio', to='api.recurso'),
        ),
        migrations.AlterUniqueTogether(
            name='musculospordia',
            unique_together={('dia_de_rutina', 'grupo_muscular')},
        ),
        migrations.AlterUniqueTogether(
            name='recursosdeejercicio',
            unique_together={('ejercicio', 'recurso')},
        ),
    ]
