# Generated by Django 5.0.6 on 2024-06-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_diaderutina_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='anotaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
