# Generated by Django 5.0.6 on 2024-07-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_canton_distrito_provincia_alter_miembro_anotaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='anotaciones',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
