# Generated by Django 5.0.6 on 2024-07-09 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_miembro_anotaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.miembro')),
            ],
            options={
                'indexes': [models.Index(fields=['miembro', 'timestamp'], name='api_asisten_miembro_463aec_idx'), models.Index(fields=['timestamp'], name='api_asisten_timesta_76c297_idx'), models.Index(fields=['miembro'], name='api_asisten_miembro_301f39_idx')],
            },
        ),
    ]
