# Generated by Django 5.0.6 on 2024-07-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='api.miembro'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
