# Generated by Django 5.0.6 on 2024-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_asistencia_miembro_alter_asistencia_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
