# Generated by Django 5.0.6 on 2024-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_miembro_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
