# Generated by Django 5.0.6 on 2024-08-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_miembro_cedula'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiembroTipo',
            new_name='Plan',
        ),
    ]
