# Generated by Django 5.0.6 on 2024-08-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_miembrotipo_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembro',
            old_name='tipo_membresia',
            new_name='plan_membresia',
        ),
    ]
