# Generated by Django 5.0.6 on 2024-08-14 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_rename_tipo_membresia_miembro_plan_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='plan_membresia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='plan_membresia', to='api.plan'),
        ),
    ]
