# Generated by Django 5.0.6 on 2024-08-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_miembro_plan_membresia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembro',
            old_name='plan_membresia',
            new_name='plan',
        ),
    ]
