# Generated by Django 5.0.6 on 2024-08-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_rename_plan_membresia_miembro_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='es_frecuente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miembro',
            name='marcador',
            field=models.BooleanField(default=False),
        ),
    ]
