# Generated by Django 5.0.6 on 2024-08-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisElec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODELE', models.CharField(max_length=6)),
                ('PROVINCIA', models.CharField(max_length=10)),
                ('CANTON', models.CharField(max_length=20)),
                ('DISTRITO', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEDULA', models.CharField(max_length=9)),
                ('CODELEC', models.CharField(max_length=6)),
                ('RELLENO', models.CharField(max_length=1)),
                ('FECHACADUC', models.CharField(max_length=8)),
                ('JUNTA', models.CharField(max_length=5)),
                ('NOMBRE', models.CharField(max_length=30)),
                ('PRIMER_APELLIDO', models.CharField(max_length=26)),
                ('SEGUNDO_APELLIDO', models.CharField(max_length=26)),
            ],
            options={
                'indexes': [models.Index(fields=['CEDULA', 'NOMBRE', 'PRIMER_APELLIDO', 'SEGUNDO_APELLIDO'], name='persona_per_CEDULA_2cccb0_idx'), models.Index(fields=['NOMBRE'], name='persona_per_NOMBRE_30c0ec_idx'), models.Index(fields=['PRIMER_APELLIDO'], name='persona_per_PRIMER__32cc73_idx')],
            },
        ),
    ]
