# Generated by Django 5.0.6 on 2024-08-05 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diselec',
            name='CODELE',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='CEDULA',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='CODELEC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='CODIGO_ELECTORAL', to='persona.diselec', to_field='CODELE'),
        ),
    ]
