# Generated by Django 5.0.6 on 2024-08-05 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_diselec_codele_alter_persona_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='CODELEC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.diselec', to_field='CODELE'),
        ),
    ]
