# Generated by Django 5.0.6 on 2024-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_persona_codelec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diselec',
            name='CODELE',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='persona',
            name='CEDULA',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='persona',
            name='CODELEC',
            field=models.CharField(max_length=6),
        ),
    ]
