# Generated by Django 5.0.6 on 2024-08-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_diselec_codele_alter_persona_cedula_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisElec',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
